# Markdownlint configuration for Claude Code Oracle Skills

# Default state for all rules
default: true

# Line length - disabled for skill files (code blocks can be long)
MD013: false

# Allow inline HTML (for badges, etc.)
MD033: false

# Allow multiple headers with same content (e.g., "Example" in different sections)
MD024:
  siblings_only: true

# Allow trailing punctuation in headers (for questions)
MD026:
  punctuation: ".,;:!"

# Code block style
MD046:
  style: fenced

# Fenced code should have language specified
MD040: true

# Allow bare URLs (useful for quick links)
MD034: false
